In [14]:
import torch
import torchvision
from torchvision import transforms, datasets

In [2]:
a = torch.ones(1,1)
a

tensor([[1.]])

In [7]:
y = torch.rand([5,5])
y

tensor([[0.0812, 0.6277, 0.9157, 0.1135, 0.8646],
        [0.7678, 0.2513, 0.1030, 0.3626, 0.5774],
        [0.0537, 0.1088, 0.1540, 0.2606, 0.7799],
        [0.9789, 0.4219, 0.0315, 0.6890, 0.4497],
        [0.9357, 0.8480, 0.9065, 0.4053, 0.0545]])

In [13]:
y.view([1, 25])

tensor([[0.0812, 0.6277, 0.9157, 0.1135, 0.8646, 0.7678, 0.2513, 0.1030, 0.3626,
         0.5774, 0.0537, 0.1088, 0.1540, 0.2606, 0.7799, 0.9789, 0.4219, 0.0315,
         0.6890, 0.4497, 0.9357, 0.8480, 0.9065, 0.4053, 0.0545]])